l_russian:
 CONFIGURATOR_TOOLTIP: "Настрой себе игру"
 
 nw_configurator_title: "§RКонфигуратор мода§!"
 
 #1 ряд
 ger_title: "§HГермания:§!"
 ger_reich: "Путь Третьего Рейха"
 ger_kaiser: "Путь Кайзера"
 ger_revolt: "Путь Револьтрейха"
 ger_democrat: "Демократический путь"
 
 hun_title: "§HВенгрия:§!"
 hun_hbbrg: "Восстановить империю Габсбургов"
 hbbrg_fash: "Империя Габсбургов: путь Христианской Империи"
 hbbrg_monarch: "Империя Габсбургов: путь Австро-Венгрии"
 hbbrg_danubian: "Империя Габсбургов: путь Дунайской федерации/СШЕ"
 
 fra_title: "§HФранция:§!"
 fra_little_entente: "Путь "Малой антанты""
 fra_go_with_britain: "Пробританский путь"
 fra_support_the_left: "Коммунистический путь"
 fra_support_the_right: "Фашистский путь"
 fra_support_tro: "Марксистский путь"
 
 mex_title: "§HМексика§!"
 mex_commi: "Коммунистический путь"
 mex_troz: "Марксистский путь"
 mex_fash: "Фашистский путь"
 mex_dem: "Демократический путь"
 
 jap_title: "§HЯпония§!"
 jap_troz: "Марксистский путь"
 jap_commi: "Коммунистический путь"
 jap_nokodoha: "Борьба с "Кодоха""
 jap_kodoha: "Поддержка "Кодоха""
 jap_dem: "Демократический путь"
 
 man_title: "§HМанчжоу-Го§!"
 man_obedience: "Послушание"
 man_aggressiveness: "Напористость"
 
 tur_title: "§HТурция§!"
 tur_neut_ismet_inenu: "Путь Исмета Инёню"
 tur_neut_cakmak: "Путь Чакмака"
 tur_dem: "Демократический путь"
 tur_fash: "Фашистский путь"
 tur_troz: "Марксистский путь"
 tur_commi: "Коммунистический путь"
 tur_monarch: "Монархический путь"
 
 #2 ряд
 can_title: "§HКанада:§!"
 can_with_uk: "Пробританская политика"
 can_naa: "Североамериканский Альянс"
 can_fash: "Фашистский путь"
 can_commi: "Коммунистический путь"
 
 saf_title: "§HЮжная Африка:§!"
 saf_with_uk: "Пробританская политика"
 saf_fash: "Фашистский путь"
 saf_commi: "Коммунистический путь"
 
 raj_title: "§HИндия:§!"
 raj_with_uk: "Пробританская политика"
 raj_fash: "Фашистский путь"
 raj_commi: "Коммунистический путь"
 
 ast_title: "§HАвстралия:§!"
 ast_with_uk: "Пробританская политика"
 ast_self: "Самостоятельность"
 ast_fash: "Фашистский путь"
 ast_commi: "Коммунистический путь"
 
 nzl_title: "§HНовая Зеландия:§!"
 nzl_with_uk: "Пробританская политика"
 nzl_self: "Самостоятельность"
 nzl_fash: "Фашистский путь"
 nzl_commi: "Коммунистический путь"
 
 generic_all_flag: "§MВыбрана настройка в конфигураторе§!"
 
 RESET_CONFIGURATOR_TOOLTIP: "Сброс приоритетов"
 ENEMY_SWITCH_TOOLTIP: "Активация приоритета AI-игроку"
 GENERIC_TOOLTIP: "§RГенерик фокусы будут полностью разблокированы§!"
 RANDOM_TOOLTIP: "§RСгенерить рандомные галочки!§!"
 
 NW_conf_on: "£trigger_yes"
 NW_conf_off: "£trigger_no"
 
 